### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by l-yampolsky** [davidemms/STRIDE#1]
Would it be possible to post the list of python packages (ideally command lines to install them) necessary to run STRIDE? I have numpy and scipy installed (via Anaconda), having trouble installing scipy.special.

Thanks!

**Comment by davidemms** [comment]
Hi

Thanks for pointing that out, I've updated the README page to say that numpy and scipy are required. I'm not sure why you'd be having problems with scipy.special. I've checked on their [documentation page](https://docs.scipy.org/doc/) and scipy.special is available in scipy right back to the earliest version they have listed on their website (version 0.7). Did you manage to resolve this?

All the best
David
