### ISSUE TITLE
NameError: global name 'ete' is not defined

### ISSUE THREAD

**Issue by l-yampolsky** [davidemms/STRIDE#2]
Dear Colleagues,
I am trying to run STRIDE and I am getting this:

python --version
Python 2.7.5

python ../../../stride/stride.py -s second_dash -S STAG_ResultsApr23/SpeciesTree.tre -d Gene_Trees
****************************************************************************
*     STRIDE: Species Tree Root Inference from Gene Duplication Events     *
*                                                                          *
****************************************************************************
Analysing 18623 gene trees
Traceback (most recent call last):
  File "../../../stride/stride.py", line 738, in <module>
    args.Func(args)
  File "../../../stride/stride.py", line 701, in Main_Full
    roots, clusters_counter, _, nSupport, clades, species, all_stride_dup_genes = GetRoot(args.Species_tree, args.gene_trees, GeneToSpecies, nProcs)
  File "../../../stride/stride.py", line 512, in GetRoot
    speciesTree = ete.Tree(speciesTreeFN, format=1)                    
NameError: global name 'ete' is not defined

Any idea what I might be doing wrong?
Thanks!

**Comment by komalck88** [comment]
I am now facing the exact same issue. Did you find out what was wrong?

-Cheers,
Komal

**Comment by davidemms** [comment]
Hi

Sorry for the delay in the response, I hadn't received any notifications for the issues being submitted. You need to install the ETE tree library. It will work with ete2 or ete3.

All the best
David
