### ISSUE TITLE
ete3.parser.newick.NewickError: Unexpected newick format

### ISSUE THREAD

**Issue by komalck88** [davidemms/STRIDE#3]
Hi @davidemms ,

**I am facing a problem regrading the tree formats. STRIDE successfully mapped my gene trees to species tree. However, it faces problem while writing results. Below is what it says..**

"Analysing 13764 gene trees
Identified 328 non-terminal duplications.
328 support the best roots and 0 contradict them.
Most parsimonious outgroup(s) for species tree:
{T37pepT37, Trichodermaguizhouense, TrichodermareeseiQM6a, njaugeneprotevmmodelT37, Trichodermagamsii2, TrichodermareeseiRUTC30, TrichodermaasperellumCBS43397, Escovopsisweberi, Trichodermaharzianum, Trichodermaparareesei, TrichodermalongibrachiatumATCC18648, Trichodermaafroharzianum, TrichodermaatrovirideIMI206040, Trichodermacitrinoviride, TrichodermavirensGv298, TrichodermaharzianumCBS22695, Trichodermahamatum, Trichodermagamsii}
{T37pepT37, Trichodermaguizhouense, TrichodermareeseiQM6a, njaugeneprotevmmodelT37, Trichodermagamsii2, TrichodermareeseiRUTC30, TrichodermaasperellumCBS43397, TrichodermalongibrachiatumATCC18648, Trichodermaharzianum, Trichodermaparareesei, Trichodermaafroharzianum, TrichodermaatrovirideIMI206040, Trichodermacitrinoviride, TrichodermavirensGv298, TrichodermaharzianumCBS22695, Trichodermahamatum, Trichodermagamsii}
{ChaetomiumglobosumCBS14851, NeurosporacrassaOR74A}
{Clavicepspurpurea201, CordycepsconfragosaRCEF1005, Purpureocilliumlilacinum2, MetarhiziumacridumCQMa102, Pochoniachlamydosporia170, Purpureocilliumlilacinum, BeauveriabassianaARSEF2860, MetarhiziumrileyiRCEF4871, Ustilaginoideavirens, MetarhiziumanisopliaeARSEF549, CordycepsmilitarisCM01}
{NectriahaematococcampVI77134, FusariumgraminearumPH1, StachybotryschartarumIBT7711, StachybotryschlorohalonataIBT40285, FusariumpseudograminearumCS3096, StachybotryschartarumIBT40293, Fusariumoxysporumfsplycopersici4287, FusariumfujikuroiIMI58289}
Etc...
7 possible roots

Results written to:
/home/akop/Desktop/Python/STRIDE_ResultsAug22
Traceback (most recent call last):
  File "stride.py", line 738, in <module>
    args.Func(args)
  File "stride.py", line 719, in Main_Full
    WriteResults(args.Species_tree, roots, species, clades, clusters_counter, outputDir)
  File "stride.py", line 602, in WriteResults
    species_tree = ete.Tree(species_tree_fn_or_text)
  File "/usr/local/lib/python2.7/dist-packages/ete3/coretype/tree.py", line 211, in __init__
    quoted_names=quoted_node_names)
  File "/usr/local/lib/python2.7/dist-packages/ete3/parser/newick.py", line 251, in read_newick
    return _read_newick_from_string(nw, root_node, matcher, format, quoted_names)
  File "/usr/local/lib/python2.7/dist-packages/ete3/parser/newick.py", line 326, in _read_newick_from_string
    _read_node_data(closing_internal, current_parent, "internal", matcher, formatcode)
  File "/usr/local/lib/python2.7/dist-packages/ete3/parser/newick.py", line 430, in _read_node_data
    raise NewickError("Unexpected newick format '%s' " %subnw[0:50])
ete3.parser.newick.NewickError: Unexpected newick format 'N1:0.088216' 
You may want to check other newick loading flags like 'format' or 'quoted_node_names'. "

**I do not have quotes in the node names. Nor any special characters.. Here is a part of my species tree**

((NeurosporacrassaOR74A:0.267255,ChaetomiumglobosumCBS14851:0.310549)N1:0.088216,(((NectriahaematococcampVI77134:0.106968,((FusariumgraminearumPH1:0.0271987,FusariumpseudograminearumCS3096:0.0178459)N14:0.0721002,(FusariumfujikuroiIMI58289:0.0238737,...

**Could you kindly tell me what seems to be the problem and how can I solve it?** 

Cheers,
Komal

**Comment by davidemms** [comment]
Hi Komal

Would you be able to upload the full species tree or email it to me and I will take a look.

Thanks 
David

**Comment by davidemms** [comment]
Hi Komal

I've added some code to make STRIDE more flexible with the species tree format. Would you be able to download the latest version from here: https://github.com/davidemms/STRIDE and try it out. 

Thanks
David

**Comment by komalck88** [comment]
Ok, I am going to try it right now. Thank you for responding :)

**Comment by komalck88** [comment]
Hi again,

It worked with new version of STRIDE, which you shared above!!  Thanks a lot!

Cheers,
Komal

**Comment by davidemms** [comment]
Great, thanks for letting me know.
