### ISSUE TITLE
STRIDE error: "Some genes cannot be mapped to species in the species tree"

### ISSUE THREAD

**Issue by Jung19911124** [davidemms/STRIDE#4]
Hi, 

I am trying to perform STRIDE on my STAG output.
Hoever, I got error message like "Some genes cannot be mapped to species in the species tree"
and finally it said:
Traceback (most recent call last):
  File "/home/jung/Tools/STRIDE/stride/stride.py", line 741, in <module>
    args.Func(args)
  File "/home/jung/Tools/STRIDE/stride/stride.py", line 704, in Main_Full
    roots, clusters_counter, _, nSupport, clades, species, all_stride_dup_genes = GetRoot(args.Species_tree, args.gene_trees, GeneToSpecies, nProcs)
  File "/home/jung/Tools/STRIDE/stride/stride.py", line 518, in GetRoot
    for l, stride_dup_genes in list_of_dicts:
TypeError: 'NoneType' object is not iterable

What am i gonna do?

**Comment by davidemms** [comment]
Hi

In the error message, right where it says "Some genes cannot be mapped to species in the species tree" it should also print out the filename of the tree that this applies to and then the set of names it is having problems mapping to the species tree. Have you looked at this information? Does it help you identify the where the problems are mapping the  genes to species?

All the best
David

**Comment by davidemms** [comment]
Just to clarify for other users, the error message will tell you which genes couldn't be mapped to the species and it should be possible from there what names needs to be corrected in the input files.
