### ISSUE TITLE
Quick Question about the leaf values

### ISSUE THREAD

**Issue by jdarias93** [davidemms/STRIDE#5]
Dear Dr. Emms,

I was wondering if you could please explain where the leaf values in the rooted STRIDE tree come from. I understand that internal node and tree backbone values come from the number of strongly supported duplications, but I'm still having trouble figuring out where the leaf values come from. In my case, the leaf values seem to be a lot higher than most of the internal and backbone node values. Thank you in advance.

**Comment by davidemms** [comment]
Hi Josh

It's generally true that you will find a lot more duplications in present day species. Basically, genes get duplicated frequently but most of these duplicates will be lost again over evolutionary time scales. When you look at the genome of a species, you get a snapshot of this and see all the genes that are currently duplicated even if most of these duplicates will be lost over the next millions of years. These duplicates are very easy to identify in a gene tree, it is just two sister genes (leaves) from the same species. 

All the best
David
